# Generated by Django 3.2.5 on 2022-03-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('school', models.CharField(max_length=20, verbose_name='学校')),
                ('major', models.CharField(default='', max_length=20, verbose_name='专业')),
            ],
            options={
                'ordering': ('school', 'major'),
            },
        ),
    ]
