# Generated by Django 3.2.5 on 2022-03-22 09:05

import app.scrambler
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('date', models.AutoField(primary_key=True, serialize=False)),
                ('item_222', models.JSONField(default=app.scrambler.scrambler, verbose_name='222')),
                ('item_333', models.JSONField(default=app.scrambler.scrambler, verbose_name='333')),
                ('item_444', models.JSONField(default=app.scrambler.scrambler, verbose_name='444')),
                ('item_555', models.JSONField(default=app.scrambler.scrambler, verbose_name='555')),
                ('item_666', models.JSONField(default=app.scrambler.scrambler, verbose_name='666')),
                ('item_777', models.JSONField(default=app.scrambler.scrambler, verbose_name='777')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('222', '222'), ('333', '333'), ('444', '444'), ('555', '555'), ('666', '666'), ('777', '777'), ('sk', 'sk'), ('py', 'py'), ('sq1', 'sq1'), ('minx', 'minx'), ('clock', 'clock'), ('FMC', 'FMC'), ('333oh', '333oh'), ('333bf', '333bf'), ('444bf', '444bf'), ('555bf', '555bf')], default='333', max_length=10, verbose_name='参赛项目')),
                ('time1', models.FloatField(default=0.0, verbose_name='时间1')),
                ('time2', models.FloatField(default=0.0, verbose_name='时间2')),
                ('time3', models.FloatField(default=0.0, verbose_name='时间3')),
                ('time4', models.FloatField(blank=True, default=0.0, null=True, verbose_name='时间4')),
                ('time5', models.FloatField(blank=True, default=0.0, null=True, verbose_name='时间5')),
                ('video', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='视频BV号')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.competition')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
