# Generated by Django 3.2.5 on 2022-03-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_competition_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scramble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_333', models.JSONField(null=True, verbose_name='333')),
            ],
        ),
    ]
