# Generated by Django 3.2.5 on 2022-03-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_scramble'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scramble',
        ),
        migrations.AddField(
            model_name='competition',
            name='item_222',
            field=models.JSONField(default=[1, 1, 1, 1, 0], verbose_name='222'),
        ),
        migrations.AddField(
            model_name='competition',
            name='item_333',
            field=models.JSONField(default=[1, 0, 1, 0, 1], verbose_name='333'),
        ),
        migrations.AddField(
            model_name='competition',
            name='item_444',
            field=models.JSONField(default=[0, 0, 1, 1, 0], verbose_name='444'),
        ),
        migrations.AddField(
            model_name='competition',
            name='item_555',
            field=models.JSONField(default=[0, 0, 1, 0, 0], verbose_name='555'),
        ),
        migrations.AddField(
            model_name='competition',
            name='item_666',
            field=models.JSONField(default=[1, 0, 1, 1, 0], verbose_name='666'),
        ),
        migrations.AddField(
            model_name='competition',
            name='item_777',
            field=models.JSONField(default=[0, 1, 1, 1, 1], verbose_name='777'),
        ),
    ]
