# Generated by Django 3.2.5 on 2022-03-18 14:08

import app.scrambler
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220318_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='item_222',
            field=models.JSONField(default=dict, verbose_name='222'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='item_333',
            field=models.JSONField(default=app.scrambler.scrambler, verbose_name='333'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='item_444',
            field=models.JSONField(default=app.scrambler.scrambler, verbose_name='444'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='item_555',
            field=models.JSONField(default=app.scrambler.scrambler, verbose_name='555'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='item_666',
            field=models.JSONField(default=app.scrambler.scrambler, verbose_name='666'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='item_777',
            field=models.JSONField(default=app.scrambler.scrambler, verbose_name='777'),
        ),
    ]
