# Generated by Django 3.2.5 on 2022-03-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220318_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='item_222',
            field=models.JSONField(default=[1, 1, 0, 1, 0], verbose_name='222'),
        ),
    ]
