# Generated by Django 3.2.5 on 2022-03-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_result_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='time',
        ),
        migrations.AddField(
            model_name='result',
            name='time1',
            field=models.FloatField(default=0.0, verbose_name='时间1'),
        ),
        migrations.AddField(
            model_name='result',
            name='time2',
            field=models.FloatField(default=0.0, verbose_name='时间2'),
        ),
        migrations.AddField(
            model_name='result',
            name='time3',
            field=models.FloatField(default=0.0, verbose_name='时间3'),
        ),
        migrations.AddField(
            model_name='result',
            name='time4',
            field=models.FloatField(blank=True, default=0.0, verbose_name='时间4'),
        ),
        migrations.AddField(
            model_name='result',
            name='time5',
            field=models.FloatField(blank=True, default=0.0, verbose_name='时间5'),
        ),
    ]
