# Generated by Django 3.2.5 on 2022-03-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_result_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='time4',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='时间4'),
        ),
        migrations.AlterField(
            model_name='result',
            name='time5',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='时间5'),
        ),
    ]
